import { useEffect, useState, useRef } from "react";
import {
  GitCompare,
  Sparkles,
  Upload,
  FileText,
  ChevronDown,
  ArrowLeftRight,
  X,
  Copy,
  Check,
  Search,
  Download,
  AlertCircle,
  Loader2,
  FileSpreadsheet,
  CheckCircle2,
  RotateCcw,
} from "lucide-react";
import ComparisonResult from "../components/ComparisonResult";
import DisclaimerBanner from "../components/DisclaimerBanner";
import { compareContracts, compareContractsById, getContracts } from "../services/api";
import type { ChangeItem, ContractMetadata } from "../types";

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export default function ComparisonPage() {
  const [contracts, setContracts] = useState<ContractMetadata[]>([]);
  const [mode, setMode] = useState<"existing" | "upload">("upload");
  const [contractAId, setContractAId] = useState("");
  const [contractBId, setContractBId] = useState("");
  const [fileA, setFileA] = useState<File | null>(null);
  const [fileB, setFileB] = useState<File | null>(null);
  const [summary, setSummary] = useState("");
  const [changes, setChanges] = useState<ChangeItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [filterType, setFilterType] = useState<"ALL" | "MODIFIED" | "ADDED" | "REMOVED">("ALL");
  const [searchQuery, setSearchQuery] = useState("");
  const [copiedSummary, setCopiedSummary] = useState(false);

  useEffect(() => {
    void getContracts()
      .then((items) => {
        setContracts(items);
        if (items.length >= 2) {
          setContractAId(items[0].contract_id);
          setContractBId(items[1].contract_id);
          setMode("existing");
        } else if (items.length === 1) {
          setContractAId(items[0].contract_id);
          setMode("upload");
        } else {
          setMode("upload");
        }
      })
      .catch(() => undefined);
  }, []);

  const handleSwap = () => {
    if (mode === "upload") {
      const temp = fileA;
      setFileA(fileB);
      setFileB(temp);
    } else {
      const temp = contractAId;
      setContractAId(contractBId);
      setContractBId(temp);
    }
  };

  const handleClear = () => {
    setSummary("");
    setChanges([]);
    setError(null);
    setSearchQuery("");
    setFilterType("ALL");
  };

  const handleCompare = async () => {
    setError(null);
    setLoading(true);
    try {
      let result;
      if (mode === "existing") {
        if (!contractAId || !contractBId) {
          setError("Please select both contracts to compare.");
          setLoading(false);
          return;
        }
        if (contractAId === contractBId) {
          setError("Please select two different contracts to compare.");
          setLoading(false);
          return;
        }
        result = await compareContractsById(contractAId, contractBId);
      } else {
        if (!fileA || !fileB) {
          setError("Please select both Version A and Version B contract files before comparing.");
          setLoading(false);
          return;
        }
        result = await compareContracts(fileA, fileB);
      }

      setSummary(result.ai_summary);
      setChanges(
        result.changes.map((item, index) => ({
          id: `${index}`,
          changeType: item.change_type,
          section: item.section,
          pageNumberA: item.page_number_a,
          pageNumberB: item.page_number_b,
          textA: item.text_a,
          textB: item.text_b,
        }))
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to compare contracts. Please verify files and try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleCopySummary = () => {
    if (!summary) return;
    void navigator.clipboard.writeText(summary);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  const handleExportReport = () => {
    const labelA = fileA?.name || contracts.find((c) => c.contract_id === contractAId)?.filename || "Version A";
    const labelB = fileB?.name || contracts.find((c) => c.contract_id === contractBId)?.filename || "Version B";

    const content = [
      `# Contract Comparison & Redline Report`,
      `Generated by CounselAI on ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`,
      ``,
      `**Baseline Version (A):** ${labelA}`,
      `**Revised Version (B):** ${labelB}`,
      ``,
      `## AI Redline Summary`,
      summary,
      ``,
      `## Clause-by-Clause Differences (${changes.length} total)`,
      ``,
      ...changes.map((c, i) => {
        return [
          `### ${i + 1}. [${c.changeType}] ${c.section || "Clause"}`,
          c.textA ? `- **${labelA} (p. ${c.pageNumberA ?? "—"}):**\n  > ${c.textA}` : `- **${labelA}:** (Not present)`,
          c.textB ? `- **${labelB} (p. ${c.pageNumberB ?? "—"}):**\n  > ${c.textB}` : `- **${labelB}:** (Not present)`,
          ``,
        ].join("\n");
      }),
    ].join("\n");

    const blob = new Blob([content], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `contract_comparison_${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const contractAObj = contracts.find((c) => c.contract_id === contractAId);
  const contractBObj = contracts.find((c) => c.contract_id === contractBId);

  const labelA = fileA?.name || contractAObj?.filename || "Version A";
  const labelB = fileB?.name || contractBObj?.filename || "Version B";

  const modifiedCount = changes.filter((c) => c.changeType === "MODIFIED").length;
  const addedCount = changes.filter((c) => c.changeType === "ADDED").length;
  const removedCount = changes.filter((c) => c.changeType === "REMOVED").length;

  const filteredChanges = changes.filter((change) => {
    if (filterType !== "ALL" && change.changeType !== filterType) {
      return false;
    }
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      const matchSection = change.section?.toLowerCase().includes(q) ?? false;
      const matchA = change.textA?.toLowerCase().includes(q) ?? false;
      const matchB = change.textB?.toLowerCase().includes(q) ?? false;
      return matchSection || matchA || matchB;
    }
    return true;
  });

  const canCompare =
    mode === "existing" ? Boolean(contractAId && contractBId && contractAId !== contractBId) : Boolean(fileA && fileB);

  return (
    <div className="flex flex-col gap-6">
      {/* Top Configuration Card */}
      <div className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 shadow-card">
        {/* Header with Title & Mode Toggle */}
        <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 pb-5">
          <div className="flex items-center gap-3">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent-50 text-accent-600 border border-accent-100">
              <GitCompare size={22} strokeWidth={2.2} />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-semibold text-ink-900">Compare Contract Versions</h2>
              <p className="text-xs sm:text-sm text-slate-500">
                Identify modified terms, additions, and omissions with automated redlining and AI change synthesis.
              </p>
            </div>
          </div>

          {/* Mode Switcher */}
          <div className="inline-flex rounded-xl bg-slate-100 p-1 text-xs font-medium">
            <button
              onClick={() => setMode("upload")}
              className={`flex items-center gap-1.5 rounded-lg px-3.5 py-2 transition-all ${
                mode === "upload"
                  ? "bg-white text-ink-900 shadow-xs font-semibold"
                  : "text-slate-600 hover:text-ink-900"
              }`}
            >
              <Upload size={14} />
              <span>Upload Files</span>
            </button>
            <button
              onClick={() => setMode("existing")}
              disabled={contracts.length < 2}
              title={contracts.length < 2 ? "Requires at least 2 saved contracts in your vault" : undefined}
              className={`flex items-center gap-1.5 rounded-lg px-3.5 py-2 transition-all ${
                mode === "existing"
                  ? "bg-white text-ink-900 shadow-xs font-semibold"
                  : "text-slate-600 hover:text-ink-900 disabled:opacity-45 disabled:cursor-not-allowed"
              }`}
            >
              <FileText size={14} />
              <span>Saved Contracts ({contracts.length})</span>
            </button>
          </div>
        </div>

        {/* Dual Comparison Selector Section */}
        <div className="mt-5">
          {mode === "upload" ? (
            <div className="relative grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] items-center gap-4">
              {/* Panel A */}
              <ModernFileDropzone
                label="Baseline Version (A)"
                subtitle="Original or previous agreement draft"
                file={fileA}
                badgeColor="slate"
                onFileSelected={setFileA}
                onRemove={() => setFileA(null)}
              />

              {/* Swap Button */}
              <div className="flex justify-center md:py-0">
                <button
                  type="button"
                  onClick={handleSwap}
                  title="Swap Baseline (A) and Revised (B)"
                  className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-500 shadow-xs hover:border-accent-400 hover:bg-accent-50 hover:text-accent-600 transition-all hover:scale-105 active:scale-95"
                >
                  <ArrowLeftRight size={16} />
                </button>
              </div>

              {/* Panel B */}
              <ModernFileDropzone
                label="Revised Version (B)"
                subtitle="Updated draft, counter-proposal, or redline"
                file={fileB}
                badgeColor="accent"
                onFileSelected={setFileB}
                onRemove={() => setFileB(null)}
              />
            </div>
          ) : (
            <div className="relative grid grid-cols-1 md:grid-cols-[1fr_auto_1fr] items-center gap-4">
              {/* Select A */}
              <div className="rounded-xl border border-slate-200 bg-slate-25 p-4">
                <div className="flex items-center justify-between gap-2 mb-2">
                  <span className="text-xs font-semibold uppercase tracking-wider text-slate-500">
                    Baseline Version (A)
                  </span>
                  <span className="rounded bg-slate-100 px-2 py-0.5 text-[11px] font-medium text-slate-600">
                    Original
                  </span>
                </div>
                <div className="relative">
                  <select
                    value={contractAId}
                    onChange={(e) => setContractAId(e.target.value)}
                    className="w-full appearance-none rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 pr-9 text-sm font-medium text-ink-900 outline-none hover:border-slate-300 focus:border-accent-500 transition-colors shadow-2xs cursor-pointer"
                  >
                    {contracts.map((c) => (
                      <option key={c.contract_id} value={c.contract_id}>
                        {c.filename} ({c.num_pages ?? "—"} pages)
                      </option>
                    ))}
                  </select>
                  <ChevronDown
                    size={16}
                    className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"
                  />
                </div>
                {contractAObj && (
                  <p className="mt-2 text-xs text-slate-500 flex items-center gap-1.5">
                    <FileText size={12} className="text-slate-400" />
                    <span>{contractAObj.num_pages ?? "—"} pages</span>
                    {contractAObj.upload_date && (
                      <>
                        <span className="text-slate-300">·</span>
                        <span>Saved {new Date(contractAObj.upload_date).toLocaleDateString()}</span>
                      </>
                    )}
                  </p>
                )}
              </div>

              {/* Swap Button */}
              <div className="flex justify-center md:py-0">
                <button
                  type="button"
                  onClick={handleSwap}
                  title="Swap contracts A and B"
                  className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-500 shadow-xs hover:border-accent-400 hover:bg-accent-50 hover:text-accent-600 transition-all hover:scale-105 active:scale-95"
                >
                  <ArrowLeftRight size={16} />
                </button>
              </div>

              {/* Select B */}
              <div className="rounded-xl border border-slate-200 bg-slate-25 p-4">
                <div className="flex items-center justify-between gap-2 mb-2">
                  <span className="text-xs font-semibold uppercase tracking-wider text-accent-700">
                    Revised Version (B)
                  </span>
                  <span className="rounded bg-accent-100/60 px-2 py-0.5 text-[11px] font-medium text-accent-700">
                    Comparison
                  </span>
                </div>
                <div className="relative">
                  <select
                    value={contractBId}
                    onChange={(e) => setContractBId(e.target.value)}
                    className="w-full appearance-none rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 pr-9 text-sm font-medium text-ink-900 outline-none hover:border-slate-300 focus:border-accent-500 transition-colors shadow-2xs cursor-pointer"
                  >
                    {contracts.map((c) => (
                      <option key={c.contract_id} value={c.contract_id}>
                        {c.filename} ({c.num_pages ?? "—"} pages)
                      </option>
                    ))}
                  </select>
                  <ChevronDown
                    size={16}
                    className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"
                  />
                </div>
                {contractBObj && (
                  <p className="mt-2 text-xs text-slate-500 flex items-center gap-1.5">
                    <FileText size={12} className="text-slate-400" />
                    <span>{contractBObj.num_pages ?? "—"} pages</span>
                    {contractBObj.upload_date && (
                      <>
                        <span className="text-slate-300">·</span>
                        <span>Saved {new Date(contractBObj.upload_date).toLocaleDateString()}</span>
                      </>
                    )}
                  </p>
                )}
              </div>
            </div>
          )}

          {/* Action Bar */}
          <div className="mt-5 flex flex-wrap items-center justify-between gap-3 pt-4 border-t border-slate-100">
            <div className="text-xs text-slate-400">
              {mode === "upload"
                ? "Accepted formats: PDF or DOCX up to 15MB each."
                : contracts.length < 2
                ? "Need at least 2 saved contracts to compare existing vault files."
                : "Select any two different contracts from your vault."}
            </div>

            <div className="flex items-center gap-2">
              {changes.length > 0 && (
                <button
                  onClick={handleClear}
                  type="button"
                  className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-medium text-slate-600 hover:bg-slate-50 transition-colors shadow-2xs"
                >
                  <RotateCcw size={13} />
                  Reset
                </button>
              )}
              <button
                onClick={() => void handleCompare()}
                disabled={loading || !canCompare}
                className="flex items-center justify-center gap-2 rounded-xl bg-ink-900 px-6 py-2.5 text-sm font-medium text-white shadow-xs hover:bg-ink-700 disabled:opacity-45 disabled:cursor-not-allowed transition-all"
              >
                {loading ? (
                  <>
                    <Loader2 size={16} className="animate-spin text-accent-300" />
                    <span>Analyzing differences…</span>
                  </>
                ) : (
                  <>
                    <GitCompare size={16} className="text-accent-400" />
                    <span>Compare Contracts</span>
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Error Message */}
      {error && (
        <div className="flex items-center gap-2.5 rounded-xl border border-risk-high/30 bg-risk-high/5 p-4 text-sm text-risk-high">
          <AlertCircle size={18} className="shrink-0" />
          <span>{error}</span>
        </div>
      )}

      {/* Results or Empty State */}
      {!summary && !loading ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-8 sm:p-12 text-center shadow-card">
          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-100 text-slate-400 mb-4">
            <GitCompare size={28} strokeWidth={1.8} />
          </div>
          <h3 className="text-base font-semibold text-ink-900">Select two contract versions to compare</h3>
          <p className="mx-auto mt-2 max-w-md text-xs sm:text-sm text-slate-500 leading-relaxed">
            Upload two document drafts or choose two saved contracts above. CounselAI will detect modified clauses,
            added obligations, and deletions with AI redline explanations.
          </p>

          <div className="mx-auto mt-8 grid max-w-2xl grid-cols-1 gap-4 sm:grid-cols-3 text-left">
            <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-4">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-amber-100 text-amber-700 mb-2.5 font-bold text-xs">
                Δ
              </span>
              <h4 className="text-xs font-semibold text-ink-900">Modified Clauses</h4>
              <p className="mt-1 text-[11px] text-slate-500 leading-normal">
                Detect altered liability limits, payment terms, or altered obligations.
              </p>
            </div>

            <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-4">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-emerald-100 text-emerald-700 mb-2.5 font-bold text-xs">
                +
              </span>
              <h4 className="text-xs font-semibold text-ink-900">Added Sections</h4>
              <p className="mt-1 text-[11px] text-slate-500 leading-normal">
                Spot new indemnities, restrictive covenants, or unexpected warranty riders.
              </p>
            </div>

            <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-4">
              <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-rose-100 text-rose-700 mb-2.5 font-bold text-xs">
                −
              </span>
              <h4 className="text-xs font-semibold text-ink-900">Deleted Terms</h4>
              <p className="mt-1 text-[11px] text-slate-500 leading-normal">
                Identify protections or rights from the baseline that were dropped in the revision.
              </p>
            </div>
          </div>
        </div>
      ) : (
        <>
          {/* AI Executive Change Summary Card */}
          {summary && (
            <div className="rounded-2xl border border-accent-100 bg-gradient-to-br from-accent-50/70 via-accent-50/40 to-white p-5 sm:p-6 shadow-card">
              <div className="flex flex-wrap items-center justify-between gap-3 border-b border-accent-100/60 pb-3">
                <div className="flex items-center gap-2">
                  <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-accent-600 text-white shadow-2xs">
                    <Sparkles size={14} />
                  </span>
                  <h3 className="font-semibold text-ink-900 text-sm sm:text-base">AI Redline Summary</h3>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopySummary}
                    className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 shadow-2xs transition-colors"
                  >
                    {copiedSummary ? (
                      <>
                        <Check size={13} className="text-emerald-600" />
                        <span className="text-emerald-600">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy size={13} />
                        <span>Copy Summary</span>
                      </>
                    )}
                  </button>

                  <button
                    onClick={handleExportReport}
                    className="flex items-center gap-1.5 rounded-lg bg-ink-900 px-3 py-1.5 text-xs font-medium text-white hover:bg-ink-700 shadow-2xs transition-colors"
                  >
                    <Download size={13} />
                    <span>Export Report</span>
                  </button>
                </div>
              </div>

              <p className="mt-3.5 text-xs sm:text-sm text-slate-700 leading-relaxed whitespace-pre-line font-sans">
                {summary}
              </p>
            </div>
          )}

          {/* Differences Section with Filter & Search Toolbar */}
          <div className="flex flex-col gap-4">
            <div className="flex flex-wrap items-center justify-between gap-3 bg-white p-4 rounded-xl border border-slate-200 shadow-xs">
              {/* Type Filter Buttons */}
              <div className="flex flex-wrap items-center gap-1.5 text-xs font-medium">
                <button
                  onClick={() => setFilterType("ALL")}
                  className={`rounded-lg px-3 py-1.5 transition-colors ${
                    filterType === "ALL"
                      ? "bg-ink-900 text-white font-semibold shadow-2xs"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200 hover:text-ink-900"
                  }`}
                >
                  All Differences ({changes.length})
                </button>
                <button
                  onClick={() => setFilterType("MODIFIED")}
                  className={`rounded-lg px-3 py-1.5 transition-colors ${
                    filterType === "MODIFIED"
                      ? "bg-amber-600 text-white font-semibold shadow-2xs"
                      : "bg-amber-50 text-amber-700 border border-amber-200/60 hover:bg-amber-100"
                  }`}
                >
                  Modified ({modifiedCount})
                </button>
                <button
                  onClick={() => setFilterType("ADDED")}
                  className={`rounded-lg px-3 py-1.5 transition-colors ${
                    filterType === "ADDED"
                      ? "bg-emerald-600 text-white font-semibold shadow-2xs"
                      : "bg-emerald-50 text-emerald-700 border border-emerald-200/60 hover:bg-emerald-100"
                  }`}
                >
                  Added ({addedCount})
                </button>
                <button
                  onClick={() => setFilterType("REMOVED")}
                  className={`rounded-lg px-3 py-1.5 transition-colors ${
                    filterType === "REMOVED"
                      ? "bg-rose-600 text-white font-semibold shadow-2xs"
                      : "bg-rose-50 text-rose-700 border border-rose-200/60 hover:bg-rose-100"
                  }`}
                >
                  Removed ({removedCount})
                </button>
              </div>

              {/* Keyword Search */}
              <div className="relative min-w-[220px] sm:w-64">
                <Search size={14} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                <input
                  type="text"
                  placeholder="Filter clauses or text…"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full rounded-lg border border-slate-200 bg-slate-50/50 py-1.5 pl-8 pr-7 text-xs text-ink-900 outline-none focus:border-accent-500 focus:bg-white transition-colors"
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery("")}
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                  >
                    <X size={12} />
                  </button>
                )}
              </div>
            </div>

            {/* Change List */}
            {filteredChanges.length === 0 ? (
              <div className="rounded-xl border border-dashed border-slate-200 bg-white p-8 text-center text-xs text-slate-500">
                No differences found matching your active filter or search query.
              </div>
            ) : (
              <div className="flex flex-col gap-3.5">
                {filteredChanges.map((change) => (
                  <ComparisonResult key={change.id} change={change} labelA={labelA} labelB={labelB} />
                ))}
              </div>
            )}

            <DisclaimerBanner compact />
          </div>
        </>
      )}
    </div>
  );
}

// -----------------------------------------------------------------------------
// Interactive Modern Drag-and-Drop File Box
// -----------------------------------------------------------------------------
function ModernFileDropzone({
  label,
  subtitle,
  file,
  badgeColor,
  onFileSelected,
  onRemove,
}: {
  label: string;
  subtitle: string;
  file: File | null;
  badgeColor: "slate" | "accent";
  onFileSelected: (file: File) => void;
  onRemove: () => void;
}) {
  const [isDragging, setIsDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    const droppedFile = e.dataTransfer.files?.[0];
    if (droppedFile) {
      onFileSelected(droppedFile);
    }
  };

  return (
    <div
      onDragOver={(e) => {
        e.preventDefault();
        setIsDragging(true);
      }}
      onDragLeave={() => setIsDragging(false)}
      onDrop={handleDrop}
      className={`relative flex flex-col rounded-xl border-2 transition-all ${
        isDragging
          ? "border-accent-500 bg-accent-50/50 scale-[1.01]"
          : file
          ? "border-slate-200 bg-white shadow-2xs"
          : "border-dashed border-slate-200 bg-slate-25 hover:border-accent-300 hover:bg-white"
      }`}
    >
      <input
        ref={inputRef}
        type="file"
        accept=".pdf,.docx"
        className="hidden"
        onChange={(e) => {
          const selected = e.target.files?.[0];
          if (selected) {
            onFileSelected(selected);
          }
        }}
      />

      <div className="p-4 sm:p-5">
        <div className="flex items-center justify-between gap-2 mb-2.5">
          <div>
            <span
              className={`text-xs font-semibold uppercase tracking-wider ${
                badgeColor === "accent" ? "text-accent-700" : "text-slate-600"
              }`}
            >
              {label}
            </span>
            <p className="text-[11px] text-slate-400">{subtitle}</p>
          </div>
          {file && (
            <span className="inline-flex items-center gap-1 rounded-md bg-emerald-50 px-2 py-0.5 text-[11px] font-medium text-emerald-700 border border-emerald-100">
              <CheckCircle2 size={11} /> Ready
            </span>
          )}
        </div>

        {file ? (
          <div className="flex items-center justify-between gap-3 rounded-lg border border-slate-100 bg-slate-50/70 p-3 mt-1">
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-accent-100 text-accent-700">
                <FileSpreadsheet size={18} />
              </div>
              <div className="min-w-0">
                <p className="truncate text-xs font-semibold text-ink-900" title={file.name}>
                  {file.name}
                </p>
                <p className="text-[10px] text-slate-400">{formatFileSize(file.size)}</p>
              </div>
            </div>

            <div className="flex items-center gap-1 shrink-0">
              <button
                type="button"
                onClick={() => inputRef.current?.click()}
                className="rounded px-2 py-1 text-xs font-medium text-accent-600 hover:bg-accent-50 transition-colors"
              >
                Change
              </button>
              <button
                type="button"
                onClick={onRemove}
                title="Remove file"
                className="rounded p-1 text-slate-400 hover:bg-slate-200 hover:text-slate-600 transition-colors"
              >
                <X size={14} />
              </button>
            </div>
          </div>
        ) : (
          <div
            onClick={() => inputRef.current?.click()}
            className="flex flex-col items-center justify-center py-4 cursor-pointer text-center group"
          >
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-white border border-slate-200 text-slate-400 shadow-2xs group-hover:border-accent-300 group-hover:text-accent-600 transition-colors mb-2">
              <Upload size={18} />
            </div>
            <p className="text-xs font-medium text-ink-900 group-hover:text-accent-600 transition-colors">
              Drop file here, or <span className="text-accent-600 underline underline-offset-2">browse</span>
            </p>
            <p className="text-[10px] text-slate-400 mt-0.5">Supports PDF or DOCX</p>
          </div>
        )}
      </div>
    </div>
  );
}
